### ISSUE TITLE
Promise wrapper method

### ISSUE THREAD

**Issue by JustinLivi** [rjz/supertest-session#21]
Would you be open to a PR that adds a mongoose-style `exec` method?

Usage would look like this:

```javascript
supertest( app )
.get( '/someRoute' )
.expect( 200 )
// wraps supertest.end in a promise
.exec()
.then( function() {
    // success
})
.catch( function( error ) {
    // failure
});
```

**Comment by rjz** [comment]
Hey, @JustinLivi! We could do this, but there might be other approaches. @benesch has a promise-based supertest extension in [supertest-as-promised](https://github.com/WhoopInc/supertest-as-promised) that @shaunc [previously wrapped](https://github.com/shaunc/supertest-session-as-promised)—would something like that suit your needs?

If the `exec`/thunk makes better sense for the use-case, it may be better to follow the pattern of extending this package externally rather than changing the API here. This library has mirrored `supertest`'s continuation-passing API fairly closely (in fact, improving agent support in 'recent' `supertest` versions has largely mooted this library's raison d'etre), and departing from it may complicate future compatibility changes.

That being said, I'd be very happy to see this extension working in some form!

**Comment by JustinLivi** [comment]
I wasn't aware of the existence of either of these modules. supertest-session-as-promised looks exactly like what I need, thanks!
